version: "3.9"
services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    command: [ "npm", "run", "start" ]
    environment:
      - MONGO_PROD="true"
      - MONGO_USER="root"
      - MONGO_PASSWORD="example"