version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend/.
    ports:
      - "4200:80"
  backend:
    build: ./backend/.
    ports:
      - "8080:8080"