version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend/.
  backend:
    build: ./backend/.
    command: [ "npm", "run", "local-compose" ]