version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  frontend:
    image: lohenl/shorty-fe
    ports:
      - "80:80"
  backend:
    image: lohenl/shorty-be
    ports:
      - "8080:8080"
    command: [ "npm", "run", "start" ]